#pragma once

#include <ATen/ATen.h>

namespace at {

struct VariableType : public Type {
  VariableType(Context* context, Type* baseType);
  virtual ScalarType scalarType() override;
  virtual Backend backend() override;
  virtual bool isCuda() override;
  virtual bool isSparse() override;
  virtual bool isDistributed() override;
  virtual std::unique_ptr<Storage> storage() override;
  virtual std::unique_ptr<Storage> storage(size_t size) override;
  virtual std::unique_ptr<Storage> storageFromBlob(void * data, int64_t size) override;
  virtual std::unique_ptr<Generator> generator() override;
  virtual const char * toString() const override;
  virtual TypeID ID() const override;
  static const char * typeString();
  Tensor unsafeTensorFromTH(void * th_pointer, bool retain) override;

  virtual void copy(const Tensor & src, Tensor & dst) override;
  virtual int64_t m_storage_offset(const Tensor & self) override;
  virtual Tensor & m_resize_(Tensor & self, IntList size) override;
  virtual Tensor & zeros_out(IntList size, Tensor & result) override;
  virtual Tensor zeros(IntList size) override;
  virtual Tensor & ones_out(IntList size, Tensor & result) override;
  virtual Tensor ones(IntList size) override;
  virtual int64_t numel(const Tensor & self) override;
  virtual Tensor & m_set_(Tensor & self, Storage & storage) override;
  virtual Tensor & m_set_(Tensor & self, Storage & sourceStorage, int64_t storage_offset, IntList size, IntList stride) override;
  virtual Tensor & m_set_(Tensor & self, Storage & sourceStorage, int64_t storage_offset, IntList size) override;
  virtual Tensor & m_set_(Tensor & self, const Tensor & source) override;
  virtual Tensor & m_set_(Tensor & self) override;
  virtual Tensor & m_fill_(Tensor & self, Scalar value) override;
  virtual bool m_is_same_size(const Tensor & self, const Tensor & other) override;
  virtual bool m_is_contiguous(const Tensor & self) override;
  virtual bool m_is_set_to(const Tensor & self, const Tensor & tensor) override;
  virtual Tensor & m_masked_fill_(Tensor & self, const Tensor & mask, Scalar value) override;
  virtual Tensor & m_masked_scatter_(Tensor & self, const Tensor & mask, const Tensor & source) override;
  virtual Tensor & masked_select_out(const Tensor & self, const Tensor & mask, Tensor & result) override;
  virtual Tensor masked_select(const Tensor & self, const Tensor & mask) override;
  virtual Tensor transpose(const Tensor & self, int64_t dim0, int64_t dim1) override;
  virtual Tensor & m_transpose_(Tensor & self, int64_t dim0, int64_t dim1) override;
  virtual Tensor t(const Tensor & self) override;
  virtual Tensor & m_t_(Tensor & self) override;
  virtual Tensor & squeeze_out(const Tensor & self, int64_t dim, Tensor & result) override;
  virtual Tensor squeeze(const Tensor & self, int64_t dim) override;
  virtual Tensor & squeeze_out(const Tensor & self, Tensor & result) override;
  virtual Tensor squeeze(const Tensor & self) override;
  virtual Tensor & m_squeeze_(Tensor & self, int64_t dim) override;
  virtual Tensor & m_squeeze_(Tensor & self) override;
  virtual Tensor & unsqueeze_out(const Tensor & self, int64_t dim, Tensor & result) override;
  virtual Tensor unsqueeze(const Tensor & self, int64_t dim) override;
  virtual Tensor & m_unsqueeze_(Tensor & self, int64_t dim) override;
  virtual Tensor & nonzero_out(const Tensor & self, Tensor & result) override;
  virtual Tensor nonzero(const Tensor & self) override;
  virtual Tensor m_contiguous(const Tensor & self) override;
  virtual Tensor m_clone(const Tensor & self) override;
  virtual Tensor m_view(const Tensor & self, IntList size) override;
  virtual Tensor m_expand(const Tensor & self, IntList size) override;
  virtual Tensor & m_resize_as_(Tensor & self, const Tensor & the_template) override;
  virtual Tensor & index_select_out(const Tensor & self, int64_t dim, const Tensor & index, Tensor & result) override;
  virtual Tensor index_select(const Tensor & self, int64_t dim, const Tensor & index) override;
  virtual Tensor & m_index_copy_(Tensor & self, int64_t dim, const Tensor & index, const Tensor & source) override;
  virtual Tensor & m_index_add_(Tensor & self, int64_t dim, const Tensor & index, const Tensor & source) override;
  virtual Tensor & m_index_fill_(Tensor & self, int64_t dim, const Tensor & index, Scalar value) override;
  virtual Tensor m_narrow(const Tensor & self, int64_t dimension, int64_t start, int64_t length) override;
  virtual Tensor m_unfold(const Tensor & self, int64_t dimension, int64_t size, int64_t step) override;
  virtual Tensor & range_out(Scalar start, Scalar end, Scalar step, Tensor & result) override;
  virtual Tensor range(Scalar start, Scalar end, Scalar step) override;
  virtual Tensor & range_out(Scalar start, Scalar end, Tensor & result) override;
  virtual Tensor range(Scalar start, Scalar end) override;
  virtual Tensor & m_scatter_(Tensor & self, int64_t dim, const Tensor & index, const Tensor & src) override;
  virtual Tensor & m_scatter_(Tensor & self, int64_t dim, const Tensor & index, Scalar value) override;
  virtual Tensor & m_scatter_add_(Tensor & self, int64_t dim, const Tensor & index, const Tensor & src) override;
  virtual Tensor & gather_out(const Tensor & self, int64_t dim, const Tensor & index, Tensor & result) override;
  virtual Tensor gather(const Tensor & self, int64_t dim, const Tensor & index) override;
  virtual void* m_data_ptr(const Tensor & self) override;
  virtual bool equal(const Tensor & self, const Tensor & other) override;
  virtual Tensor & __and___out(const Tensor & self, Scalar value, Tensor & result) override;
  virtual Tensor __and__(const Tensor & self, Scalar value) override;
  virtual Tensor & __and___out(const Tensor & self, const Tensor & other, Tensor & result) override;
  virtual Tensor __and__(const Tensor & self, const Tensor & other) override;
  virtual Tensor & __iand__(Tensor & self, Scalar value) override;
  virtual Tensor & __iand__(Tensor & self, const Tensor & other) override;
  virtual Tensor & __or___out(const Tensor & self, Scalar value, Tensor & result) override;
  virtual Tensor __or__(const Tensor & self, Scalar value) override;
  virtual Tensor & __or___out(const Tensor & self, const Tensor & other, Tensor & result) override;
  virtual Tensor __or__(const Tensor & self, const Tensor & other) override;
  virtual Tensor & __ior__(Tensor & self, Scalar value) override;
  virtual Tensor & __ior__(Tensor & self, const Tensor & other) override;
  virtual Tensor & __xor___out(const Tensor & self, Scalar value, Tensor & result) override;
  virtual Tensor __xor__(const Tensor & self, Scalar value) override;
  virtual Tensor & __xor___out(const Tensor & self, const Tensor & other, Tensor & result) override;
  virtual Tensor __xor__(const Tensor & self, const Tensor & other) override;
  virtual Tensor & __ixor__(Tensor & self, Scalar value) override;
  virtual Tensor & __ixor__(Tensor & self, const Tensor & other) override;
  virtual Tensor & __lshift___out(const Tensor & self, Scalar value, Tensor & result) override;
  virtual Tensor __lshift__(const Tensor & self, Scalar value) override;
  virtual Tensor & __lshift___out(const Tensor & self, const Tensor & other, Tensor & result) override;
  virtual Tensor __lshift__(const Tensor & self, const Tensor & other) override;
  virtual Tensor & __ilshift__(Tensor & self, Scalar value) override;
  virtual Tensor & __ilshift__(Tensor & self, const Tensor & other) override;
  virtual Tensor & __rshift___out(const Tensor & self, Scalar value, Tensor & result) override;
  virtual Tensor __rshift__(const Tensor & self, Scalar value) override;
  virtual Tensor & __rshift___out(const Tensor & self, const Tensor & other, Tensor & result) override;
  virtual Tensor __rshift__(const Tensor & self, const Tensor & other) override;
  virtual Tensor & __irshift__(Tensor & self, Scalar value) override;
  virtual Tensor & __irshift__(Tensor & self, const Tensor & other) override;
  virtual Tensor m_lt(const Tensor & self, Scalar value) override;
  virtual Tensor m_lt(const Tensor & self, const Tensor & other) override;
  virtual Tensor & m_lt_(Tensor & self, Scalar value) override;
  virtual Tensor & m_lt_(Tensor & self, const Tensor & other) override;
  virtual Tensor & lt_out(const Tensor & tensor, Scalar value, Tensor & result) override;
  virtual Tensor lt(const Tensor & tensor, Scalar value) override;
  virtual Tensor & lt_out(const Tensor & tensor, const Tensor & other, Tensor & result) override;
  virtual Tensor lt(const Tensor & tensor, const Tensor & other) override;
  virtual Tensor m_gt(const Tensor & self, Scalar value) override;
  virtual Tensor m_gt(const Tensor & self, const Tensor & other) override;
  virtual Tensor & m_gt_(Tensor & self, Scalar value) override;
  virtual Tensor & m_gt_(Tensor & self, const Tensor & other) override;
  virtual Tensor & gt_out(const Tensor & tensor, Scalar value, Tensor & result) override;
  virtual Tensor gt(const Tensor & tensor, Scalar value) override;
  virtual Tensor & gt_out(const Tensor & tensor, const Tensor & other, Tensor & result) override;
  virtual Tensor gt(const Tensor & tensor, const Tensor & other) override;
  virtual Tensor m_le(const Tensor & self, Scalar value) override;
  virtual Tensor m_le(const Tensor & self, const Tensor & other) override;
  virtual Tensor & m_le_(Tensor & self, Scalar value) override;
  virtual Tensor & m_le_(Tensor & self, const Tensor & other) override;
  virtual Tensor & le_out(const Tensor & tensor, Scalar value, Tensor & result) override;
  virtual Tensor le(const Tensor & tensor, Scalar value) override;
  virtual Tensor & le_out(const Tensor & tensor, const Tensor & other, Tensor & result) override;
  virtual Tensor le(const Tensor & tensor, const Tensor & other) override;
  virtual Tensor m_ge(const Tensor & self, Scalar value) override;
  virtual Tensor m_ge(const Tensor & self, const Tensor & other) override;
  virtual Tensor & m_ge_(Tensor & self, Scalar value) override;
  virtual Tensor & m_ge_(Tensor & self, const Tensor & other) override;
  virtual Tensor & ge_out(const Tensor & tensor, Scalar value, Tensor & result) override;
  virtual Tensor ge(const Tensor & tensor, Scalar value) override;
  virtual Tensor & ge_out(const Tensor & tensor, const Tensor & other, Tensor & result) override;
  virtual Tensor ge(const Tensor & tensor, const Tensor & other) override;
  virtual Tensor m_eq(const Tensor & self, Scalar value) override;
  virtual Tensor m_eq(const Tensor & self, const Tensor & other) override;
  virtual Tensor & m_eq_(Tensor & self, Scalar value) override;
  virtual Tensor & m_eq_(Tensor & self, const Tensor & other) override;
  virtual Tensor & eq_out(const Tensor & tensor, Scalar value, Tensor & result) override;
  virtual Tensor eq(const Tensor & tensor, Scalar value) override;
  virtual Tensor & eq_out(const Tensor & tensor, const Tensor & other, Tensor & result) override;
  virtual Tensor eq(const Tensor & tensor, const Tensor & other) override;
  virtual Tensor m_ne(const Tensor & self, Scalar value) override;
  virtual Tensor m_ne(const Tensor & self, const Tensor & other) override;
  virtual Tensor & m_ne_(Tensor & self, Scalar value) override;
  virtual Tensor & m_ne_(Tensor & self, const Tensor & other) override;
  virtual Tensor & ne_out(const Tensor & tensor, Scalar value, Tensor & result) override;
  virtual Tensor ne(const Tensor & tensor, Scalar value) override;
  virtual Tensor & ne_out(const Tensor & tensor, const Tensor & other, Tensor & result) override;
  virtual Tensor ne(const Tensor & tensor, const Tensor & other) override;
  virtual std::tuple<Tensor &,Tensor &> min_out(const Tensor & self, int64_t dim, bool keepdim, Tensor & min, Tensor & min_indices) override;
  virtual std::tuple<Tensor,Tensor> min(const Tensor & self, int64_t dim, bool keepdim) override;
  virtual std::tuple<Tensor &,Tensor &> min_out(const Tensor & self, int64_t dim, Tensor & min, Tensor & min_indices) override;
  virtual std::tuple<Tensor,Tensor> min(const Tensor & self, int64_t dim) override;
  virtual Tensor & min_out(const Tensor & self, const Tensor & other, Tensor & result) override;
  virtual Tensor min(const Tensor & self, const Tensor & other) override;
  virtual Scalar min(const Tensor & self) override;
  virtual std::tuple<Tensor &,Tensor &> max_out(const Tensor & self, int64_t dim, bool keepdim, Tensor & max, Tensor & max_indices) override;
  virtual std::tuple<Tensor,Tensor> max(const Tensor & self, int64_t dim, bool keepdim) override;
  virtual std::tuple<Tensor &,Tensor &> max_out(const Tensor & self, int64_t dim, Tensor & max, Tensor & max_indices) override;
  virtual std::tuple<Tensor,Tensor> max(const Tensor & self, int64_t dim) override;
  virtual Tensor & max_out(const Tensor & self, const Tensor & other, Tensor & result) override;
  virtual Tensor max(const Tensor & self, const Tensor & other) override;
  virtual Scalar max(const Tensor & self) override;
  virtual std::tuple<Tensor &,Tensor &> kthvalue_out(const Tensor & self, int64_t k, bool keepdim, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> kthvalue(const Tensor & self, int64_t k, bool keepdim) override;
  virtual std::tuple<Tensor &,Tensor &> kthvalue_out(const Tensor & self, int64_t k, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> kthvalue(const Tensor & self, int64_t k) override;
  virtual std::tuple<Tensor &,Tensor &> kthvalue_out(const Tensor & self, int64_t k, int64_t dim, bool keepdim, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> kthvalue(const Tensor & self, int64_t k, int64_t dim, bool keepdim) override;
  virtual std::tuple<Tensor &,Tensor &> kthvalue_out(const Tensor & self, int64_t k, int64_t dim, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> kthvalue(const Tensor & self, int64_t k, int64_t dim) override;
  virtual std::tuple<Tensor &,Tensor &> mode_out(const Tensor & self, bool keepdim, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> mode(const Tensor & self, bool keepdim) override;
  virtual std::tuple<Tensor &,Tensor &> mode_out(const Tensor & self, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> mode(const Tensor & self) override;
  virtual std::tuple<Tensor &,Tensor &> mode_out(const Tensor & self, int64_t dim, bool keepdim, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> mode(const Tensor & self, int64_t dim, bool keepdim) override;
  virtual std::tuple<Tensor &,Tensor &> mode_out(const Tensor & self, int64_t dim, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> mode(const Tensor & self, int64_t dim) override;
  virtual std::tuple<Tensor &,Tensor &> median_out(const Tensor & self, bool keepdim, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> median(const Tensor & self, bool keepdim) override;
  virtual std::tuple<Tensor &,Tensor &> median_out(const Tensor & self, int64_t dim, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> median(const Tensor & self, int64_t dim) override;
  virtual std::tuple<Tensor &,Tensor &> median_out(const Tensor & self, int64_t dim, bool keepdim, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> median(const Tensor & self, int64_t dim, bool keepdim) override;
  virtual Scalar median(const Tensor & self) override;
  virtual std::tuple<Tensor &,Tensor &> sort_out(const Tensor & self, bool descending, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> sort(const Tensor & self, bool descending) override;
  virtual std::tuple<Tensor &,Tensor &> sort_out(const Tensor & self, int64_t dim, bool descending, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> sort(const Tensor & self, int64_t dim, bool descending) override;
  virtual std::tuple<Tensor &,Tensor &> sort_out(const Tensor & self, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> sort(const Tensor & self) override;
  virtual std::tuple<Tensor &,Tensor &> sort_out(const Tensor & self, int64_t dim, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> sort(const Tensor & self, int64_t dim) override;
  virtual std::tuple<Tensor &,Tensor &> topk_out(const Tensor & self, int64_t k, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> topk(const Tensor & self, int64_t k) override;
  virtual std::tuple<Tensor &,Tensor &> topk_out(const Tensor & self, int64_t k, int64_t dim, bool largest, bool sorted, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> topk(const Tensor & self, int64_t k, int64_t dim, bool largest, bool sorted) override;
  virtual std::tuple<Tensor &,Tensor &> topk_out(const Tensor & self, int64_t k, int64_t dim, bool largest, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> topk(const Tensor & self, int64_t k, int64_t dim, bool largest) override;
  virtual std::tuple<Tensor &,Tensor &> topk_out(const Tensor & self, int64_t k, int64_t dim, Tensor & values, Tensor & indices) override;
  virtual std::tuple<Tensor,Tensor> topk(const Tensor & self, int64_t k, int64_t dim) override;
  virtual bool m_all(const Tensor & self) override;
  virtual bool m_any(const Tensor & self) override;
  virtual int64_t m_get_device(const Tensor & self) override;
  virtual Tensor & abs_out(const Tensor & self, Tensor & destination) override;
  virtual Tensor abs(const Tensor & self) override;
  virtual Tensor & m_abs_(Tensor & self) override;
  virtual Tensor & m_sigmoid_(Tensor & self) override;
  virtual Tensor & sigmoid_out(const Tensor & self, Tensor & result) override;
  virtual Tensor sigmoid(const Tensor & self) override;
  virtual Tensor & m_log_(Tensor & self) override;
  virtual Tensor & log_out(const Tensor & self, Tensor & result) override;
  virtual Tensor log(const Tensor & self) override;
  virtual Tensor & m_log1p_(Tensor & self) override;
  virtual Tensor & log1p_out(const Tensor & self, Tensor & result) override;
  virtual Tensor log1p(const Tensor & self) override;
  virtual Tensor & lgamma_out(const Tensor & self, Tensor & result) override;
  virtual Tensor lgamma(const Tensor & self) override;
  virtual Tensor & m_lgamma_(Tensor & self) override;
  virtual Tensor & m_exp_(Tensor & self) override;
  virtual Tensor & exp_out(const Tensor & self, Tensor & result) override;
  virtual Tensor exp(const Tensor & self) override;
  virtual Tensor & m_cos_(Tensor & self) override;
  virtual Tensor & cos_out(const Tensor & self, Tensor & result) override;
  virtual Tensor cos(const Tensor & self) override;
  virtual Tensor & m_acos_(Tensor & self) override;
  virtual Tensor & acos_out(const Tensor & self, Tensor & result) override;
  virtual Tensor acos(const Tensor & self) override;
  virtual Tensor & m_cosh_(Tensor & self) override;
  virtual Tensor & cosh_out(const Tensor & self, Tensor & result) override;
  virtual Tensor cosh(const Tensor & self) override;
  virtual Tensor & m_sin_(Tensor & self) override;
  virtual Tensor & sin_out(const Tensor & self, Tensor & result) override;
  virtual Tensor sin(const Tensor & self) override;
  virtual Tensor & m_asin_(Tensor & self) override;
  virtual Tensor & asin_out(const Tensor & self, Tensor & result) override;
  virtual Tensor asin(const Tensor & self) override;
  virtual Tensor & m_sinh_(Tensor & self) override;
  virtual Tensor & sinh_out(const Tensor & self, Tensor & result) override;
  virtual Tensor sinh(const Tensor & self) override;
  virtual Tensor & m_tan_(Tensor & self) override;
  virtual Tensor & tan_out(const Tensor & self, Tensor & result) override;
  virtual Tensor tan(const Tensor & self) override;
  virtual Tensor & m_atan_(Tensor & self) override;
  virtual Tensor & atan_out(const Tensor & self, Tensor & result) override;
  virtual Tensor atan(const Tensor & self) override;
  virtual Tensor & m_tanh_(Tensor & self) override;
  virtual Tensor & tanh_out(const Tensor & self, Tensor & result) override;
  virtual Tensor tanh(const Tensor & self) override;
  virtual Tensor & m_sqrt_(Tensor & self) override;
  virtual Tensor & sqrt_out(const Tensor & self, Tensor & result) override;
  virtual Tensor sqrt(const Tensor & self) override;
  virtual Tensor & m_rsqrt_(Tensor & self) override;
  virtual Tensor & rsqrt_out(const Tensor & self, Tensor & result) override;
  virtual Tensor rsqrt(const Tensor & self) override;
  virtual Tensor & m_ceil_(Tensor & self) override;
  virtual Tensor & ceil_out(const Tensor & self, Tensor & result) override;
  virtual Tensor ceil(const Tensor & self) override;
  virtual Tensor & m_floor_(Tensor & self) override;
  virtual Tensor & floor_out(const Tensor & self, Tensor & result) override;
  virtual Tensor floor(const Tensor & self) override;
  virtual Tensor & m_round_(Tensor & self) override;
  virtual Tensor & round_out(const Tensor & self, Tensor & result) override;
  virtual Tensor round(const Tensor & self) override;
  virtual Tensor & m_trunc_(Tensor & self) override;
  virtual Tensor & trunc_out(const Tensor & self, Tensor & result) override;
  virtual Tensor trunc(const Tensor & self) override;
  virtual Tensor & m_frac_(Tensor & self) override;
  virtual Tensor & frac_out(const Tensor & self, Tensor & result) override;
  virtual Tensor frac(const Tensor & self) override;
  virtual Tensor & mean_out(const Tensor & self, int64_t dim, bool keepdim, Tensor & destination) override;
  virtual Tensor mean(const Tensor & self, int64_t dim, bool keepdim) override;
  virtual Tensor & mean_out(const Tensor & self, int64_t dim, Tensor & destination) override;
  virtual Tensor mean(const Tensor & self, int64_t dim) override;
  virtual Scalar mean(const Tensor & self) override;
  virtual Tensor & var_out(const Tensor & self, int64_t dim, bool unbiased, bool keepdim, Tensor & destination) override;
  virtual Tensor var(const Tensor & self, int64_t dim, bool unbiased, bool keepdim) override;
  virtual Tensor & var_out(const Tensor & self, int64_t dim, bool keepdim, Tensor & destination) override;
  virtual Tensor var(const Tensor & self, int64_t dim, bool keepdim) override;
  virtual Tensor & var_out(const Tensor & self, int64_t dim, Tensor & destination) override;
  virtual Tensor var(const Tensor & self, int64_t dim) override;
  virtual Scalar var(const Tensor & self, bool unbiased) override;
  virtual Scalar var(const Tensor & self) override;
  virtual Tensor & std_out(const Tensor & self, int64_t dim, bool unbiased, bool keepdim, Tensor & destination) override;
  virtual Tensor std(const Tensor & self, int64_t dim, bool unbiased, bool keepdim) override;
  virtual Tensor & std_out(const Tensor & self, int64_t dim, bool keepdim, Tensor & destination) override;
  virtual Tensor std(const Tensor & self, int64_t dim, bool keepdim) override;
  virtual Tensor & std_out(const Tensor & self, int64_t dim, Tensor & destination) override;
  virtual Tensor std(const Tensor & self, int64_t dim) override;
  virtual Scalar std(const Tensor & self, bool unbiased) override;
  virtual Scalar std(const Tensor & self) override;
  virtual Tensor & norm_out(const Tensor & self, Scalar p, int64_t dim, bool keepdim, Tensor & destination) override;
  virtual Tensor norm(const Tensor & self, Scalar p, int64_t dim, bool keepdim) override;
  virtual Tensor & norm_out(const Tensor & self, Scalar p, int64_t dim, Tensor & destination) override;
  virtual Tensor norm(const Tensor & self, Scalar p, int64_t dim) override;
  virtual Scalar norm(const Tensor & self, Scalar p) override;
  virtual Scalar norm(const Tensor & self) override;
  virtual Tensor & renorm_out(const Tensor & self, Scalar p, int64_t dim, Scalar maxnorm, Tensor & destination) override;
  virtual Tensor renorm(const Tensor & self, Scalar p, int64_t dim, Scalar maxnorm) override;
  virtual Tensor & m_renorm_(Tensor & self, Scalar p, int64_t dim, Scalar maxnorm) override;
  virtual Scalar dist(const Tensor & self, const Tensor & other, Scalar p) override;
  virtual Scalar dist(const Tensor & self, const Tensor & other) override;
  virtual Tensor & reciprocal_out(const Tensor & self, Tensor & destination) override;
  virtual Tensor reciprocal(const Tensor & self) override;
  virtual Tensor & m_reciprocal_(Tensor & self) override;
  virtual Tensor & neg_out(const Tensor & self, Tensor & destination) override;
  virtual Tensor neg(const Tensor & self) override;
  virtual Tensor & m_neg_(Tensor & self) override;
  virtual Tensor & atan2_out(const Tensor & self, const Tensor & other, Tensor & destination) override;
  virtual Tensor atan2(const Tensor & self, const Tensor & other) override;
  virtual Tensor & m_atan2_(Tensor & self, const Tensor & other) override;
  virtual Tensor & pow_out(const Tensor & self, Scalar exponent, Tensor & destination) override;
  virtual Tensor pow(const Tensor & self, Scalar exponent) override;
  virtual Tensor & pow_out(const Tensor & self, const Tensor & exponent, Tensor & destination) override;
  virtual Tensor pow(const Tensor & self, const Tensor & exponent) override;
  virtual Tensor & m_pow_(Tensor & self, Scalar exponent) override;
  virtual Tensor & m_pow_(Tensor & self, const Tensor & exponent) override;
  virtual Tensor & lerp_out(const Tensor & self, const Tensor & end, Scalar weight, Tensor & destination) override;
  virtual Tensor lerp(const Tensor & self, const Tensor & end, Scalar weight) override;
  virtual Tensor & m_lerp_(Tensor & self, const Tensor & end, Scalar weight) override;
  virtual Tensor & linspace_out(Scalar start, Scalar end, int64_t steps, Tensor & result) override;
  virtual Tensor linspace(Scalar start, Scalar end, int64_t steps) override;
  virtual Tensor & linspace_out(Scalar start, Scalar end, Tensor & result) override;
  virtual Tensor linspace(Scalar start, Scalar end) override;
  virtual Tensor & logspace_out(Scalar start, Scalar end, int64_t steps, Tensor & result) override;
  virtual Tensor logspace(Scalar start, Scalar end, int64_t steps) override;
  virtual Tensor & logspace_out(Scalar start, Scalar end, Tensor & result) override;
  virtual Tensor logspace(Scalar start, Scalar end) override;
  virtual Tensor & histc_out(const Tensor & self, Tensor & destination) override;
  virtual Tensor histc(const Tensor & self) override;
  virtual Tensor & histc_out(const Tensor & self, int64_t bins, Tensor & destination) override;
  virtual Tensor histc(const Tensor & self, int64_t bins) override;
  virtual Tensor & histc_out(const Tensor & self, int64_t bins, Scalar min, Tensor & destination) override;
  virtual Tensor histc(const Tensor & self, int64_t bins, Scalar min) override;
  virtual Tensor & histc_out(const Tensor & self, int64_t bins, Scalar min, Scalar max, Tensor & destination) override;
  virtual Tensor histc(const Tensor & self, int64_t bins, Scalar min, Scalar max) override;
  virtual Tensor & m_zero_(Tensor & self) override;
  virtual Tensor & sum_out(const Tensor & self, int64_t dim, bool keepdim, Tensor & result) override;
  virtual Tensor sum(const Tensor & self, int64_t dim, bool keepdim) override;
  virtual Tensor & sum_out(const Tensor & self, int64_t dim, Tensor & result) override;
  virtual Tensor sum(const Tensor & self, int64_t dim) override;
  virtual Scalar sum(const Tensor & self) override;
  virtual Tensor & prod_out(const Tensor & self, int64_t dim, bool keepdim, Tensor & result) override;
  virtual Tensor prod(const Tensor & self, int64_t dim, bool keepdim) override;
  virtual Tensor & prod_out(const Tensor & self, int64_t dim, Tensor & result) override;
  virtual Tensor prod(const Tensor & self, int64_t dim) override;
  virtual Scalar prod(const Tensor & self) override;
  virtual Tensor & cumsum_out(const Tensor & self, int64_t dim, Tensor & result) override;
  virtual Tensor cumsum(const Tensor & self, int64_t dim) override;
  virtual Tensor & cumprod_out(const Tensor & self, int64_t dim, Tensor & result) override;
  virtual Tensor cumprod(const Tensor & self, int64_t dim) override;
  virtual Tensor & sign_out(const Tensor & self, Tensor & result) override;
  virtual Tensor sign(const Tensor & self) override;
  virtual Tensor & m_sign_(Tensor & self) override;
  virtual Scalar trace(const Tensor & self) override;
  virtual Tensor & add_out(const Tensor & self, Scalar value, const Tensor & other, Tensor & result) override;
  virtual Tensor add(const Tensor & self, Scalar value, const Tensor & other) override;
  virtual Tensor & add_out(const Tensor & self, Scalar value, SparseTensor other, Tensor & result) override;
  virtual Tensor add(const Tensor & self, Scalar value, SparseTensor other) override;
  virtual Tensor & add_out(const Tensor & self, Scalar value, Tensor & result) override;
  virtual Tensor add(const Tensor & self, Scalar value) override;
  virtual Tensor & add_out(const Tensor & self, const Tensor & other, Tensor & result) override;
  virtual Tensor add(const Tensor & self, const Tensor & other) override;
  virtual Tensor & add_out(const Tensor & self, SparseTensor other, Tensor & result) override;
  virtual Tensor add(const Tensor & self, SparseTensor other) override;
  virtual Tensor & m_add_(Tensor & self, Scalar value, const Tensor & other) override;
  virtual Tensor & m_add_(Tensor & self, Scalar value, SparseTensor other) override;
  virtual Tensor & m_add_(Tensor & self, Scalar value) override;
  virtual Tensor & m_add_(Tensor & self, const Tensor & other) override;
  virtual Tensor & m_add_(Tensor & self, SparseTensor other) override;
  virtual Tensor & sub_out(const Tensor & self, Scalar value, const Tensor & other, Tensor & result) override;
  virtual Tensor sub(const Tensor & self, Scalar value, const Tensor & other) override;
  virtual Tensor & sub_out(const Tensor & self, Scalar value, Tensor & result) override;
  virtual Tensor sub(const Tensor & self, Scalar value) override;
  virtual Tensor & sub_out(const Tensor & self, const Tensor & other, Tensor & result) override;
  virtual Tensor sub(const Tensor & self, const Tensor & other) override;
  virtual Tensor & m_sub_(Tensor & self, Scalar value, const Tensor & other) override;
  virtual Tensor & m_sub_(Tensor & self, Scalar value) override;
  virtual Tensor & m_sub_(Tensor & self, const Tensor & other) override;
  virtual Tensor & mul_out(const Tensor & self, Scalar value, Tensor & result) override;
  virtual Tensor mul(const Tensor & self, Scalar value) override;
  virtual Tensor & mul_out(const Tensor & self, const Tensor & other, Tensor & result) override;
  virtual Tensor mul(const Tensor & self, const Tensor & other) override;
  virtual Tensor & m_mul_(Tensor & self, Scalar value) override;
  virtual Tensor & m_mul_(Tensor & self, const Tensor & other) override;
  virtual Tensor & div_out(const Tensor & self, Scalar value, Tensor & result) override;
  virtual Tensor div(const Tensor & self, Scalar value) override;
  virtual Tensor & div_out(const Tensor & self, const Tensor & other, Tensor & result) override;
  virtual Tensor div(const Tensor & self, const Tensor & other) override;
  virtual Tensor & m_div_(Tensor & self, Scalar value) override;
  virtual Tensor & m_div_(Tensor & self, const Tensor & other) override;
  virtual Tensor & fmod_out(const Tensor & self, Scalar value, Tensor & result) override;
  virtual Tensor fmod(const Tensor & self, Scalar value) override;
  virtual Tensor & fmod_out(const Tensor & self, const Tensor & other, Tensor & result) override;
  virtual Tensor fmod(const Tensor & self, const Tensor & other) override;
  virtual Tensor & m_fmod_(Tensor & self, Scalar value) override;
  virtual Tensor & m_fmod_(Tensor & self, const Tensor & other) override;
  virtual Tensor & remainder_out(const Tensor & self, Scalar value, Tensor & result) override;
  virtual Tensor remainder(const Tensor & self, Scalar value) override;
  virtual Tensor & remainder_out(const Tensor & self, const Tensor & other, Tensor & result) override;
  virtual Tensor remainder(const Tensor & self, const Tensor & other) override;
  virtual Tensor & m_remainder_(Tensor & self, Scalar value) override;
  virtual Tensor & m_remainder_(Tensor & self, const Tensor & other) override;
  virtual Tensor & clamp_out(const Tensor & self, Scalar min, Scalar max, Tensor & destination) override;
  virtual Tensor clamp(const Tensor & self, Scalar min, Scalar max) override;
  virtual Tensor & clamp_out(const Tensor & self, Scalar min, Tensor & result) override;
  virtual Tensor clamp(const Tensor & self, Scalar min) override;
  virtual Tensor & m_clamp_(Tensor & self, Scalar min, Scalar max) override;
  virtual Tensor & m_clamp_(Tensor & self, Scalar min) override;
  virtual Scalar dot(const Tensor & self, const Tensor & tensor) override;
  virtual Tensor & tril_out(const Tensor & self, int64_t diagonal, Tensor & destination) override;
  virtual Tensor tril(const Tensor & self, int64_t diagonal) override;
  virtual Tensor & tril_out(const Tensor & self, Tensor & destination) override;
  virtual Tensor tril(const Tensor & self) override;
  virtual Tensor & m_tril_(Tensor & self, int64_t diagonal) override;
  virtual Tensor & m_tril_(Tensor & self) override;
  virtual Tensor & triu_out(const Tensor & self, int64_t diagonal, Tensor & destination) override;
  virtual Tensor triu(const Tensor & self, int64_t diagonal) override;
  virtual Tensor & triu_out(const Tensor & self, Tensor & destination) override;
  virtual Tensor triu(const Tensor & self) override;
  virtual Tensor & m_triu_(Tensor & self, int64_t diagonal) override;
  virtual Tensor & m_triu_(Tensor & self) override;
  virtual Tensor & cross_out(const Tensor & self, const Tensor & other, int64_t dim, Tensor & destination) override;
  virtual Tensor cross(const Tensor & self, const Tensor & other, int64_t dim) override;
  virtual Tensor & cross_out(const Tensor & self, const Tensor & other, Tensor & destination) override;
  virtual Tensor cross(const Tensor & self, const Tensor & other) override;
  virtual Tensor & eye_out(int64_t n, Tensor & result) override;
  virtual Tensor eye(int64_t n) override;
  virtual Tensor & eye_out(int64_t n, int64_t m, Tensor & result) override;
  virtual Tensor eye(int64_t n, int64_t m) override;
  virtual Tensor & diag_out(const Tensor & self, int64_t diagonal, Tensor & result) override;
  virtual Tensor diag(const Tensor & self, int64_t diagonal) override;
  virtual Tensor & diag_out(const Tensor & self, Tensor & result) override;
  virtual Tensor diag(const Tensor & self) override;
  virtual Tensor & addmm_out(Scalar beta, const Tensor & self, Scalar alpha, const Tensor & mat1, const Tensor & mat2, Tensor & result) override;
  virtual Tensor addmm(Scalar beta, const Tensor & self, Scalar alpha, const Tensor & mat1, const Tensor & mat2) override;
  virtual Tensor & addmm_out(Scalar beta, const Tensor & self, const Tensor & mat1, const Tensor & mat2, Tensor & result) override;
  virtual Tensor addmm(Scalar beta, const Tensor & self, const Tensor & mat1, const Tensor & mat2) override;
  virtual Tensor & addmm_out(const Tensor & self, const Tensor & mat1, const Tensor & mat2, Tensor & result) override;
  virtual Tensor addmm(const Tensor & self, const Tensor & mat1, const Tensor & mat2) override;
  virtual Tensor & m_addmm_(Tensor & self, Scalar beta, Scalar alpha, const Tensor & mat1, const Tensor & mat2) override;
  virtual Tensor & m_addmm_(Tensor & self, Scalar beta, const Tensor & mat1, const Tensor & mat2) override;
  virtual Tensor & m_addmm_(Tensor & self, const Tensor & mat1, const Tensor & mat2) override;
  virtual Tensor & addmv_out(Scalar beta, const Tensor & self, Scalar alpha, const Tensor & mat, const Tensor & vec, Tensor & result) override;
  virtual Tensor addmv(Scalar beta, const Tensor & self, Scalar alpha, const Tensor & mat, const Tensor & vec) override;
  virtual Tensor & addmv_out(Scalar beta, const Tensor & self, const Tensor & mat, const Tensor & vec, Tensor & result) override;
  virtual Tensor addmv(Scalar beta, const Tensor & self, const Tensor & mat, const Tensor & vec) override;
  virtual Tensor & addmv_out(const Tensor & self, const Tensor & mat, const Tensor & vec, Tensor & result) override;
  virtual Tensor addmv(const Tensor & self, const Tensor & mat, const Tensor & vec) override;
  virtual Tensor & m_addmv_(Tensor & self, Scalar beta, Scalar alpha, const Tensor & mat, const Tensor & vec) override;
  virtual Tensor & m_addmv_(Tensor & self, Scalar beta, const Tensor & mat, const Tensor & vec) override;
  virtual Tensor & m_addmv_(Tensor & self, const Tensor & mat, const Tensor & vec) override;
  virtual Tensor & addr_out(Scalar beta, const Tensor & self, Scalar alpha, const Tensor & vec1, const Tensor & vec2, Tensor & result) override;
  virtual Tensor addr(Scalar beta, const Tensor & self, Scalar alpha, const Tensor & vec1, const Tensor & vec2) override;
  virtual Tensor & addr_out(Scalar beta, const Tensor & self, const Tensor & vec1, const Tensor & vec2, Tensor & result) override;
  virtual Tensor addr(Scalar beta, const Tensor & self, const Tensor & vec1, const Tensor & vec2) override;
  virtual Tensor & addr_out(const Tensor & self, const Tensor & vec1, const Tensor & vec2, Tensor & result) override;
  virtual Tensor addr(const Tensor & self, const Tensor & vec1, const Tensor & vec2) override;
  virtual Tensor & m_addr_(Tensor & self, Scalar beta, Scalar alpha, const Tensor & vec1, const Tensor & vec2) override;
  virtual Tensor & m_addr_(Tensor & self, Scalar beta, const Tensor & vec1, const Tensor & vec2) override;
  virtual Tensor & m_addr_(Tensor & self, const Tensor & vec1, const Tensor & vec2) override;
  virtual Tensor & ger_out(const Tensor & self, const Tensor & vec2, Tensor & result) override;
  virtual Tensor ger(const Tensor & self, const Tensor & vec2) override;
  virtual Tensor & mv_out(const Tensor & self, const Tensor & vec, Tensor & result) override;
  virtual Tensor mv(const Tensor & self, const Tensor & vec) override;
  virtual Tensor & mm_out(const Tensor & self, const Tensor & mat2, Tensor & result) override;
  virtual Tensor mm(const Tensor & self, const Tensor & mat2) override;
  virtual Tensor & bmm_out(const Tensor & self, const Tensor & mat2, Tensor & result) override;
  virtual Tensor bmm(const Tensor & self, const Tensor & mat2) override;
  virtual Tensor & addbmm_out(Scalar beta, const Tensor & self, Scalar alpha, const Tensor & batch1, const Tensor & batch2, Tensor & result) override;
  virtual Tensor addbmm(Scalar beta, const Tensor & self, Scalar alpha, const Tensor & batch1, const Tensor & batch2) override;
  virtual Tensor & addbmm_out(Scalar beta, const Tensor & self, const Tensor & batch1, const Tensor & batch2, Tensor & result) override;
  virtual Tensor addbmm(Scalar beta, const Tensor & self, const Tensor & batch1, const Tensor & batch2) override;
  virtual Tensor & addbmm_out(const Tensor & self, const Tensor & batch1, const Tensor & batch2, Tensor & result) override;
  virtual Tensor addbmm(const Tensor & self, const Tensor & batch1, const Tensor & batch2) override;
  virtual Tensor & m_addbmm_(Tensor & self, Scalar beta, Scalar alpha, const Tensor & batch1, const Tensor & batch2) override;
  virtual Tensor & m_addbmm_(Tensor & self, Scalar beta, const Tensor & batch1, const Tensor & batch2) override;
  virtual Tensor & m_addbmm_(Tensor & self, const Tensor & batch1, const Tensor & batch2) override;
  virtual Tensor & baddbmm_out(Scalar beta, const Tensor & self, Scalar alpha, const Tensor & batch1, const Tensor & batch2, Tensor & result) override;
  virtual Tensor baddbmm(Scalar beta, const Tensor & self, Scalar alpha, const Tensor & batch1, const Tensor & batch2) override;
  virtual Tensor & baddbmm_out(Scalar beta, const Tensor & self, const Tensor & batch1, const Tensor & batch2, Tensor & result) override;
  virtual Tensor baddbmm(Scalar beta, const Tensor & self, const Tensor & batch1, const Tensor & batch2) override;
  virtual Tensor & baddbmm_out(const Tensor & self, const Tensor & batch1, const Tensor & batch2, Tensor & result) override;
  virtual Tensor baddbmm(const Tensor & self, const Tensor & batch1, const Tensor & batch2) override;
  virtual Tensor & m_baddbmm_(Tensor & self, Scalar beta, Scalar alpha, const Tensor & batch1, const Tensor & batch2) override;
  virtual Tensor & m_baddbmm_(Tensor & self, Scalar beta, const Tensor & batch1, const Tensor & batch2) override;
  virtual Tensor & m_baddbmm_(Tensor & self, const Tensor & batch1, const Tensor & batch2) override;
  virtual Tensor & addcmul_out(const Tensor & self, Scalar value, const Tensor & tensor1, const Tensor & tensor2, Tensor & result) override;
  virtual Tensor addcmul(const Tensor & self, Scalar value, const Tensor & tensor1, const Tensor & tensor2) override;
  virtual Tensor & addcmul_out(const Tensor & self, const Tensor & tensor1, const Tensor & tensor2, Tensor & result) override;
  virtual Tensor addcmul(const Tensor & self, const Tensor & tensor1, const Tensor & tensor2) override;
  virtual Tensor & m_addcmul_(Tensor & self, Scalar value, const Tensor & tensor1, const Tensor & tensor2) override;
  virtual Tensor & m_addcmul_(Tensor & self, const Tensor & tensor1, const Tensor & tensor2) override;
  virtual Tensor & addcdiv_out(const Tensor & self, Scalar value, const Tensor & tensor1, const Tensor & tensor2, Tensor & result) override;
  virtual Tensor addcdiv(const Tensor & self, Scalar value, const Tensor & tensor1, const Tensor & tensor2) override;
  virtual Tensor & addcdiv_out(const Tensor & self, const Tensor & tensor1, const Tensor & tensor2, Tensor & result) override;
  virtual Tensor addcdiv(const Tensor & self, const Tensor & tensor1, const Tensor & tensor2) override;
  virtual Tensor & m_addcdiv_(Tensor & self, Scalar value, const Tensor & tensor1, const Tensor & tensor2) override;
  virtual Tensor & m_addcdiv_(Tensor & self, const Tensor & tensor1, const Tensor & tensor2) override;
  virtual std::tuple<Tensor &,Tensor &> gesv_out(const Tensor & self, const Tensor & A, Tensor & solution, Tensor & lu) override;
  virtual std::tuple<Tensor,Tensor> gesv(const Tensor & self, const Tensor & A) override;
  virtual std::tuple<Tensor &,Tensor &> gels_out(const Tensor & self, const Tensor & A, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> gels(const Tensor & self, const Tensor & A) override;
  virtual std::tuple<Tensor &,Tensor &> trtrs_out(const Tensor & self, const Tensor & A, bool upper, bool transpose, bool unitriangular, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> trtrs(const Tensor & self, const Tensor & A, bool upper, bool transpose, bool unitriangular) override;
  virtual std::tuple<Tensor &,Tensor &> trtrs_out(const Tensor & self, const Tensor & A, bool upper, bool transpose, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> trtrs(const Tensor & self, const Tensor & A, bool upper, bool transpose) override;
  virtual std::tuple<Tensor &,Tensor &> trtrs_out(const Tensor & self, const Tensor & A, bool upper, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> trtrs(const Tensor & self, const Tensor & A, bool upper) override;
  virtual std::tuple<Tensor &,Tensor &> trtrs_out(const Tensor & self, const Tensor & A, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> trtrs(const Tensor & self, const Tensor & A) override;
  virtual std::tuple<Tensor &,Tensor &> symeig_out(const Tensor & self, bool eigenvectors, bool upper, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> symeig(const Tensor & self, bool eigenvectors, bool upper) override;
  virtual std::tuple<Tensor &,Tensor &> symeig_out(const Tensor & self, bool eigenvectors, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> symeig(const Tensor & self, bool eigenvectors) override;
  virtual std::tuple<Tensor &,Tensor &> symeig_out(const Tensor & self, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> symeig(const Tensor & self) override;
  virtual std::tuple<Tensor &,Tensor &> eig_out(const Tensor & self, bool eigenvectors, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> eig(const Tensor & self, bool eigenvectors) override;
  virtual std::tuple<Tensor &,Tensor &> eig_out(const Tensor & self, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> eig(const Tensor & self) override;
  virtual std::tuple<Tensor &,Tensor &,Tensor &> svd_out(const Tensor & self, bool some, Tensor & res1, Tensor & res2, Tensor & res3) override;
  virtual std::tuple<Tensor,Tensor,Tensor> svd(const Tensor & self, bool some) override;
  virtual std::tuple<Tensor &,Tensor &,Tensor &> svd_out(const Tensor & self, Tensor & res1, Tensor & res2, Tensor & res3) override;
  virtual std::tuple<Tensor,Tensor,Tensor> svd(const Tensor & self) override;
  virtual Tensor & inverse_out(const Tensor & self, Tensor & output) override;
  virtual Tensor inverse(const Tensor & self) override;
  virtual Tensor & potrf_out(const Tensor & self, bool upper, Tensor & output) override;
  virtual Tensor potrf(const Tensor & self, bool upper) override;
  virtual Tensor & potrf_out(const Tensor & self, Tensor & output) override;
  virtual Tensor potrf(const Tensor & self) override;
  virtual Tensor & potrs_out(const Tensor & self, const Tensor & input2, bool upper, Tensor & result) override;
  virtual Tensor potrs(const Tensor & self, const Tensor & input2, bool upper) override;
  virtual Tensor & potrs_out(const Tensor & self, const Tensor & input2, Tensor & result) override;
  virtual Tensor potrs(const Tensor & self, const Tensor & input2) override;
  virtual Tensor & potri_out(const Tensor & self, bool upper, Tensor & output) override;
  virtual Tensor potri(const Tensor & self, bool upper) override;
  virtual Tensor & potri_out(const Tensor & self, Tensor & output) override;
  virtual Tensor potri(const Tensor & self) override;
  virtual std::tuple<Tensor &,Tensor &> pstrf_out(const Tensor & self, bool upper, Scalar tol, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> pstrf(const Tensor & self, bool upper, Scalar tol) override;
  virtual std::tuple<Tensor &,Tensor &> pstrf_out(const Tensor & self, bool upper, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> pstrf(const Tensor & self, bool upper) override;
  virtual std::tuple<Tensor &,Tensor &> pstrf_out(const Tensor & self, Scalar tol, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> pstrf(const Tensor & self, Scalar tol) override;
  virtual std::tuple<Tensor &,Tensor &> pstrf_out(const Tensor & self, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> pstrf(const Tensor & self) override;
  virtual std::tuple<Tensor &,Tensor &> qr_out(const Tensor & self, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> qr(const Tensor & self) override;
  virtual std::tuple<Tensor &,Tensor &> geqrf_out(const Tensor & self, Tensor & res1, Tensor & res2) override;
  virtual std::tuple<Tensor,Tensor> geqrf(const Tensor & self) override;
  virtual std::tuple<Tensor &,const Tensor &> orgqr_out(const Tensor & self, const Tensor & input2, Tensor & result) override;
  virtual std::tuple<Tensor,const Tensor &> orgqr(const Tensor & self, const Tensor & input2) override;
  virtual std::tuple<Tensor &,const Tensor &> ormqr_out(const Tensor & self, const Tensor & input2, const Tensor & input3, bool left, bool transpose, Tensor & result) override;
  virtual std::tuple<Tensor,const Tensor &> ormqr(const Tensor & self, const Tensor & input2, const Tensor & input3, bool left, bool transpose) override;
  virtual std::tuple<Tensor &,const Tensor &> ormqr_out(const Tensor & self, const Tensor & input2, const Tensor & input3, bool left, Tensor & result) override;
  virtual std::tuple<Tensor,const Tensor &> ormqr(const Tensor & self, const Tensor & input2, const Tensor & input3, bool left) override;
  virtual std::tuple<Tensor &,const Tensor &> ormqr_out(const Tensor & self, const Tensor & input2, const Tensor & input3, Tensor & result) override;
  virtual std::tuple<Tensor,const Tensor &> ormqr(const Tensor & self, const Tensor & input2, const Tensor & input3) override;
  virtual std::tuple<Tensor &,Tensor &> btrifact_out(const Tensor & info, bool pivot, const Tensor & self, Tensor & result, Tensor & pivots) override;
  virtual std::tuple<Tensor,Tensor> btrifact(const Tensor & info, bool pivot, const Tensor & self) override;
  virtual std::tuple<Tensor &,Tensor &> btrifact_out(const Tensor & info, const Tensor & self, Tensor & result, Tensor & pivots) override;
  virtual std::tuple<Tensor,Tensor> btrifact(const Tensor & info, const Tensor & self) override;
  virtual std::tuple<Tensor &,Tensor &> btrifact_out(bool pivot, const Tensor & self, Tensor & result, Tensor & pivots) override;
  virtual std::tuple<Tensor,Tensor> btrifact(bool pivot, const Tensor & self) override;
  virtual std::tuple<Tensor &,Tensor &> btrifact_out(const Tensor & self, Tensor & result, Tensor & pivots) override;
  virtual std::tuple<Tensor,Tensor> btrifact(const Tensor & self) override;
  virtual Tensor & btrisolve_out(const Tensor & self, const Tensor & LU_data, const Tensor & LU_pivots, Tensor & result) override;
  virtual Tensor btrisolve(const Tensor & self, const Tensor & LU_data, const Tensor & LU_pivots) override;
  virtual Tensor & randperm_out(Generator & generator, int64_t n, Tensor & result) override;
  virtual Tensor randperm(Generator & generator, int64_t n) override;
  virtual Tensor & randperm_out(int64_t n, Tensor & result) override;
  virtual Tensor randperm(int64_t n) override;
  virtual Tensor & multinomial_out(Generator & generator, const Tensor & self, int64_t num_samples, bool replacement, Tensor & result) override;
  virtual Tensor multinomial(Generator & generator, const Tensor & self, int64_t num_samples, bool replacement) override;
  virtual Tensor & multinomial_out(Generator & generator, const Tensor & self, int64_t num_samples, Tensor & result) override;
  virtual Tensor multinomial(Generator & generator, const Tensor & self, int64_t num_samples) override;
  virtual Tensor & multinomial_out(const Tensor & self, int64_t num_samples, bool replacement, Tensor & result) override;
  virtual Tensor multinomial(const Tensor & self, int64_t num_samples, bool replacement) override;
  virtual Tensor & multinomial_out(const Tensor & self, int64_t num_samples, Tensor & result) override;
  virtual Tensor multinomial(const Tensor & self, int64_t num_samples) override;
  virtual Tensor & m_uniform_(Tensor & self, Generator & generator, double from, double to) override;
  virtual Tensor & m_uniform_(Tensor & self, Generator & generator, double from) override;
  virtual Tensor & m_uniform_(Tensor & self, double from, double to) override;
  virtual Tensor & m_uniform_(Tensor & self, Generator & generator) override;
  virtual Tensor & m_uniform_(Tensor & self, double from) override;
  virtual Tensor & m_uniform_(Tensor & self) override;
  virtual Tensor & m_cauchy_(Tensor & self, Generator & generator, double median, double sigma) override;
  virtual Tensor & m_cauchy_(Tensor & self, Generator & generator, double median) override;
  virtual Tensor & m_cauchy_(Tensor & self, double median, double sigma) override;
  virtual Tensor & m_cauchy_(Tensor & self, Generator & generator) override;
  virtual Tensor & m_cauchy_(Tensor & self, double median) override;
  virtual Tensor & m_cauchy_(Tensor & self) override;
  virtual Tensor & m_log_normal_(Tensor & self, Generator & generator, double mean, double std) override;
  virtual Tensor & m_log_normal_(Tensor & self, Generator & generator, double mean) override;
  virtual Tensor & m_log_normal_(Tensor & self, double mean, double std) override;
  virtual Tensor & m_log_normal_(Tensor & self, Generator & generator) override;
  virtual Tensor & m_log_normal_(Tensor & self, double mean) override;
  virtual Tensor & m_log_normal_(Tensor & self) override;
  virtual Tensor & rand_out(Generator & generator, IntList size, Tensor & result) override;
  virtual Tensor rand(Generator & generator, IntList size) override;
  virtual Tensor & rand_out(IntList size, Tensor & result) override;
  virtual Tensor rand(IntList size) override;
  virtual Tensor & randn_out(Generator & generator, IntList size, Tensor & result) override;
  virtual Tensor randn(Generator & generator, IntList size) override;
  virtual Tensor & randn_out(IntList size, Tensor & result) override;
  virtual Tensor randn(IntList size) override;
  virtual Tensor & m_geometric_(Tensor & self, Generator & generator, double p) override;
  virtual Tensor & m_geometric_(Tensor & self, double p) override;
  virtual int64_t m_size(const Tensor & self, int64_t dim) override;
  virtual int64_t m_stride(const Tensor & self, int64_t dim) override;
  virtual Tensor tensor(Storage & storage, int64_t storageOffset, IntList size, IntList stride) override;
  virtual Tensor tensor(Storage & storage, int64_t storageOffset, IntList size) override;
  virtual Tensor tensor(IntList size, IntList stride) override;
  virtual Tensor tensor(IntList size) override;
  virtual Tensor tensor() override;
  virtual Tensor & select_out(const Tensor & self, int dim, int64_t sliceIndex, Tensor & result) override;
  virtual Tensor select(const Tensor & self, int dim, int64_t sliceIndex) override;
  virtual Tensor & m_assign_(Tensor & self, const Tensor & src) override;
  virtual Tensor & cat_out(TensorList tensors, int dim, Tensor & self) override;
  virtual Tensor cat(TensorList tensors, int dim) override;
  virtual void Abs_updateOutput(const Tensor & input, const Tensor & output) override;
  virtual void Abs_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput) override;
  virtual void AbsCriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage) override;
  virtual void AbsCriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage) override;
  virtual void BCECriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage, const Tensor & weights) override;
  virtual void BCECriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage) override;
  virtual void BCECriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage, const Tensor & weights) override;
  virtual void BCECriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage) override;
  virtual void ClassNLLCriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage, const Tensor & weights, const Tensor & total_weight, int64_t ignore_index) override;
  virtual void ClassNLLCriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage, const Tensor & total_weight, int64_t ignore_index) override;
  virtual void ClassNLLCriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage, const Tensor & weights, const Tensor & total_weight, int64_t ignore_index) override;
  virtual void ClassNLLCriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage, const Tensor & total_weight, int64_t ignore_index) override;
  virtual void SpatialClassNLLCriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage, const Tensor & weights, const Tensor & total_weight, int64_t ignore_index) override;
  virtual void SpatialClassNLLCriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage, const Tensor & total_weight, int64_t ignore_index) override;
  virtual void SpatialClassNLLCriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage, const Tensor & weights, const Tensor & total_weight, int64_t ignore_index) override;
  virtual void SpatialClassNLLCriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage, const Tensor & total_weight, int64_t ignore_index) override;
  virtual void ELU_updateOutput(const Tensor & input, const Tensor & output, Scalar alpha, bool inplace) override;
  virtual void ELU_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & output, Scalar alpha, bool inplace) override;
  virtual void DistKLDivCriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage) override;
  virtual void DistKLDivCriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage) override;
  virtual void GatedLinear_updateOutput(const Tensor & input, const Tensor & output, int dim) override;
  virtual void GatedLinear_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, int dim) override;
  virtual void HardShrink_updateOutput(const Tensor & input, const Tensor & output, Scalar lambda) override;
  virtual void HardShrink_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, Scalar lambda) override;
  virtual void HardTanh_updateOutput(const Tensor & input, const Tensor & output, Scalar min_val, Scalar max_val, bool inplace) override;
  virtual void HardTanh_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, Scalar min_val, Scalar max_val, bool inplace) override;
  virtual void L1Cost_updateOutput(const Tensor & input, const Tensor & output) override;
  virtual void L1Cost_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput) override;
  virtual void L1Cost_updateGradInput(const Tensor & input, const Tensor & gradInput) override;
  virtual void LeakyReLU_updateOutput(const Tensor & input, const Tensor & output, Scalar negval, bool inplace) override;
  virtual void LeakyReLU_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, Scalar negval, bool inplace) override;
  virtual void GRUFused_updateOutput(const Tensor & input, const Tensor & hidden, const Tensor & bias1, const Tensor & bias2, const Tensor & hx, const Tensor & output, const Tensor & storage) override;
  virtual void GRUFused_updateOutput(const Tensor & input, const Tensor & hidden, const Tensor & bias1, const Tensor & hx, const Tensor & output, const Tensor & storage) override;
  virtual void GRUFused_updateOutput(const Tensor & input, const Tensor & hidden, const Tensor & hx, const Tensor & output, const Tensor & storage) override;
  virtual void GRUFused_updateGradInput(const Tensor & gradInInput, const Tensor & gradInHidden, const Tensor & gradOutput, const Tensor & gradInputHx, const Tensor & storage) override;
  virtual void LSTMFused_updateOutput(const Tensor & input, const Tensor & hidden, const Tensor & bias1, const Tensor & bias2, const Tensor & cell, const Tensor & output, const Tensor & outputCell) override;
  virtual void LSTMFused_updateOutput(const Tensor & input, const Tensor & hidden, const Tensor & bias1, const Tensor & cell, const Tensor & output, const Tensor & outputCell) override;
  virtual void LSTMFused_updateOutput(const Tensor & input, const Tensor & hidden, const Tensor & cell, const Tensor & output, const Tensor & outputCell) override;
  virtual void LSTMFused_updateGradInput(const Tensor & storage, const Tensor & gradInGates, const Tensor & cx, const Tensor & cy, const Tensor & gradOutput, const Tensor & gradOutputCell, const Tensor & gradInputCx) override;
  virtual void LogSigmoid_updateOutput(const Tensor & input, const Tensor & output, const Tensor & buffer) override;
  virtual void LogSigmoid_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & buffer) override;
  virtual void LogSoftMax_updateOutput(const Tensor & input, const Tensor & output) override;
  virtual void LogSoftMax_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & output) override;
  virtual void MarginCriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage, Scalar margin) override;
  virtual void MarginCriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage, Scalar margin) override;
  virtual void SoftMarginCriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage) override;
  virtual void SoftMarginCriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage) override;
  virtual void MSECriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage) override;
  virtual void MSECriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage) override;
  virtual void MultiLabelMarginCriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, const Tensor & isTarget, bool sizeAverage) override;
  virtual void MultiLabelMarginCriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, const Tensor & isTarget, bool sizeAverage) override;
  virtual void MultiMarginCriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage, int p, const Tensor & weights, Scalar margin) override;
  virtual void MultiMarginCriterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage, int p, Scalar margin) override;
  virtual void MultiMarginCriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage, int p, const Tensor & weights, Scalar margin) override;
  virtual void MultiMarginCriterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage, int p, Scalar margin) override;
  virtual void PReLU_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, int64_t nOutputPlane) override;
  virtual void PReLU_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, int64_t nOutputPlane) override;
  virtual void PReLU_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & gradWeight, const Tensor & gradWeightBuf, const Tensor & gradWeightBuf2, int64_t nOutputPlane, Scalar scale) override;
  virtual void Linear_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & addBuffer) override;
  virtual void Linear_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight) override;
  virtual void Linear_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & bias, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & addBuffer, Scalar scale) override;
  virtual void RReLU_updateOutput(const Tensor & input, const Tensor & output, const Tensor & noise, Scalar lower, Scalar upper, bool train, bool inplace, Generator & generator) override;
  virtual void RReLU_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & noise, Scalar lower, Scalar upper, bool train, bool inplace) override;
  virtual void Sigmoid_updateOutput(const Tensor & input, const Tensor & output) override;
  virtual void Sigmoid_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & output) override;
  virtual void Sigmoid_updateGradInput(const Tensor & gradOutput, const Tensor & gradInput, const Tensor & output) override;
  virtual void SmoothL1Criterion_updateOutput(const Tensor & input, const Tensor & target, const Tensor & output, bool sizeAverage) override;
  virtual void SmoothL1Criterion_updateGradInput(const Tensor & input, const Tensor & target, const Tensor & gradInput, bool sizeAverage) override;
  virtual void SoftMax_updateOutput(const Tensor & input, const Tensor & output) override;
  virtual void SoftMax_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & output) override;
  virtual void SoftPlus_updateOutput(const Tensor & input, const Tensor & output, Scalar beta, Scalar threshold) override;
  virtual void SoftPlus_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & output, Scalar beta, Scalar threshold) override;
  virtual void SoftShrink_updateOutput(const Tensor & input, const Tensor & output, Scalar lambda) override;
  virtual void SoftShrink_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, Scalar lambda) override;
  virtual void IndexLinear_updateOutput(const Tensor & keys, int64_t keysOffset, const Tensor & values, const Tensor & sizes, const Tensor & cumSumSizes, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & normalizedValues, int train) override;
  virtual void IndexLinear_accGradParameters(const Tensor & keys, int64_t keysOffset, const Tensor & values, const Tensor & sizes, const Tensor & cumSumSizes, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & weight, const Tensor & bias, const Tensor & valuesBuffer, Scalar weightDecay, Scalar scale) override;
  virtual void SparseLinear_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias) override;
  virtual void SparseLinear_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & weight, const Tensor & bias, Scalar weightDecay, Scalar scale) override;
  virtual void Sqrt_updateOutput(const Tensor & input, const Tensor & output, Scalar eps) override;
  virtual void Sqrt_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & output) override;
  virtual void Square_updateOutput(const Tensor & input, const Tensor & output) override;
  virtual void Square_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput) override;
  virtual void Tanh_updateOutput(const Tensor & input, const Tensor & output) override;
  virtual void Tanh_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & output) override;
  virtual void Tanh_updateGradInput(const Tensor & gradOutput, const Tensor & gradInput, const Tensor & output) override;
  virtual void Threshold_updateOutput(const Tensor & input, const Tensor & output, Scalar threshold, Scalar val, bool inplace) override;
  virtual void Threshold_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, Scalar threshold, Scalar val, bool inplace) override;
  virtual void TemporalConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, int kW, int dW, int inputFrameSize, int outputFrameSize) override;
  virtual void TemporalConvolution_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, int kW, int dW) override;
  virtual void TemporalConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, int kW, int dW, Scalar scale) override;
  virtual void TemporalMaxPooling_updateOutput(const Tensor & input, const Tensor & output, const Tensor & indices, int kW, int dW) override;
  virtual void TemporalMaxPooling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & indices, int kW, int dW) override;
  virtual void TemporalSubSampling_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, int kW, int dW, int inputFrameSize) override;
  virtual void TemporalSubSampling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, int kW, int dW) override;
  virtual void TemporalSubSampling_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, int kW, int dW, Scalar scale) override;
  virtual void TemporalRowConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & finput, const Tensor & fgradInput, int kW, int dW, int padW, bool featFirst) override;
  virtual void TemporalRowConvolution_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & finput, const Tensor & fgradInput, int kW, int dW, int padW, bool featFirst) override;
  virtual void TemporalRowConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & finput, const Tensor & fgradInput, int kW, int dW, int padW, bool featFirst, Scalar scale) override;
  virtual void BatchNormalization_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & running_mean, const Tensor & running_var, const Tensor & save_mean, const Tensor & save_std, bool train, double momentum, double eps) override;
  virtual void BatchNormalization_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & running_mean, const Tensor & running_var, const Tensor & save_mean, const Tensor & save_std, bool train, double momentum, double eps) override;
  virtual void BatchNormalization_updateOutput(const Tensor & input, const Tensor & output, const Tensor & running_mean, const Tensor & running_var, const Tensor & save_mean, const Tensor & save_std, bool train, double momentum, double eps) override;
  virtual void BatchNormalization_backward(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & weight, const Tensor & running_mean, const Tensor & running_var, const Tensor & save_mean, const Tensor & save_std, bool train, double scale, double eps) override;
  virtual void BatchNormalization_backward(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & running_mean, const Tensor & running_var, const Tensor & save_mean, const Tensor & save_std, bool train, double scale, double eps) override;
  virtual void BatchNormalization_backward(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & gradWeight, const Tensor & running_mean, const Tensor & running_var, const Tensor & save_mean, const Tensor & save_std, bool train, double scale, double eps) override;
  virtual void BatchNormalization_backward(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & running_mean, const Tensor & running_var, const Tensor & save_mean, const Tensor & save_std, bool train, double scale, double eps) override;
  virtual void BatchNormalization_backward(const Tensor & input, const Tensor & gradOutput, const Tensor & running_mean, const Tensor & running_var, const Tensor & save_mean, const Tensor & save_std, bool train, double scale, double eps) override;
  virtual void SpatialConvolutionMap_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & connTable, int nInputPlane, int nOutputPlane, int dW, int dH) override;
  virtual void SpatialConvolutionMap_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & bias, const Tensor & connTable, int nInputPlane, int nOutputPlane, int dW, int dH) override;
  virtual void SpatialConvolutionMap_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & connTable, int nInputPlane, int nOutputPlane, int dW, int dH, Scalar scale) override;
  virtual void SpatialConvolutionMM_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & finput, const Tensor & fgradInput, int kW, int kH, int dW, int dH, int padW, int padH) override;
  virtual void SpatialConvolutionMM_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & finput, const Tensor & fgradInput, int kW, int kH, int dW, int dH, int padW, int padH) override;
  virtual void SpatialConvolutionMM_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & finput, const Tensor & fgradInput, int kW, int kH, int dW, int dH, int padW, int padH) override;
  virtual void SpatialConvolutionMM_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & finput, const Tensor & fgradInput, int kW, int kH, int dW, int dH, int padW, int padH, Scalar scale) override;
  virtual void SpatialConvolutionMM_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & finput, const Tensor & fgradInput, int kW, int kH, int dW, int dH, int padW, int padH, Scalar scale) override;
  virtual void SpatialDepthWiseConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & finput, const Tensor & fgradInput, int kW, int kH, int dW, int dH, int padW, int padH) override;
  virtual void SpatialDepthWiseConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & finput, const Tensor & fgradInput, int kW, int kH, int dW, int dH, int padW, int padH) override;
  virtual void SpatialDepthWiseConvolution_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & finput, const Tensor & fgradInput, int kW, int kH, int dW, int dH, int padW, int padH) override;
  virtual void SpatialDepthWiseConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & finput, const Tensor & fgradInput, int kW, int kH, int dW, int dH, int padW, int padH, Scalar scale) override;
  virtual void SpatialDepthWiseConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & finput, const Tensor & fgradInput, int kW, int kH, int dW, int dH, int padW, int padH, Scalar scale) override;
  virtual void SpatialConvolutionLocal_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & finput, const Tensor & fgradInput, int kW, int kH, int dW, int dH, int padW, int padH, int64_t inputWidth, int64_t inputHeight, int64_t outputWidth, int64_t outputHeight) override;
  virtual void SpatialConvolutionLocal_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & finput, const Tensor & fgradInput, int kW, int kH, int dW, int dH, int padW, int padH, int64_t inputWidth, int64_t inputHeight, int64_t outputWidth, int64_t outputHeight) override;
  virtual void SpatialConvolutionLocal_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & finput, const Tensor & fgradInput, int kW, int kH, int dW, int dH, int padW, int padH, int64_t inputWidth, int64_t inputHeight, int64_t outputWidth, int64_t outputHeight, Scalar scale) override;
  virtual void SpatialAdaptiveMaxPooling_updateOutput(const Tensor & input, const Tensor & output, const Tensor & indices, int owidth, int oheight) override;
  virtual void SpatialAdaptiveMaxPooling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & indices) override;
  virtual void SpatialAdaptiveAveragePooling_updateOutput(const Tensor & input, const Tensor & output, int owidth, int oheight) override;
  virtual void SpatialAdaptiveAveragePooling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput) override;
  virtual void SpatialAveragePooling_updateOutput(const Tensor & input, const Tensor & output, int kW, int kH, int dW, int dH, int padW, int padH, bool ceil_mode, bool count_include_pad) override;
  virtual void SpatialAveragePooling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, int kW, int kH, int dW, int dH, int padW, int padH, bool ceil_mode, bool count_include_pad) override;
  virtual void SpatialFractionalMaxPooling_updateOutput(const Tensor & input, const Tensor & output, int outputW, int outputH, int poolSizeW, int poolSizeH, const Tensor & indices, const Tensor & randomSamples) override;
  virtual void SpatialFractionalMaxPooling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, int outputW, int outputH, int poolSizeW, int poolSizeH, const Tensor & indices) override;
  virtual void SpatialFullConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & columns, const Tensor & ones, int kW, int kH, int dW, int dH, int padW, int padH, int adjW, int adjH) override;
  virtual void SpatialFullConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & columns, const Tensor & ones, int kW, int kH, int dW, int dH, int padW, int padH, int adjW, int adjH) override;
  virtual void SpatialFullConvolution_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & gradColumns, int kW, int kH, int dW, int dH, int padW, int padH, int adjW, int adjH) override;
  virtual void SpatialFullConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & columns, const Tensor & ones, int kW, int kH, int dW, int dH, int padW, int padH, int adjW, int adjH, Scalar scale) override;
  virtual void SpatialFullConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & columns, const Tensor & ones, int kW, int kH, int dW, int dH, int padW, int padH, int adjW, int adjH, Scalar scale) override;
  virtual void SpatialFullConvolutionMap_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & connTable, int nInputPlane, int nOutputPlane, int dW, int dH) override;
  virtual void SpatialFullConvolutionMap_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & bias, const Tensor & connTable, int nInputPlane, int nOutputPlane, int dW, int dH) override;
  virtual void SpatialFullConvolutionMap_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & connTable, int nInputPlane, int nOutputPlane, int dW, int dH, Scalar scale) override;
  virtual void SpatialDilatedConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & columns, const Tensor & ones, int kW, int kH, int dW, int dH, int padW, int padH, int dilationW, int dilationH) override;
  virtual void SpatialDilatedConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & columns, const Tensor & ones, int kW, int kH, int dW, int dH, int padW, int padH, int dilationW, int dilationH) override;
  virtual void SpatialDilatedConvolution_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & gradColumns, int kW, int kH, int dW, int dH, int padW, int padH, int dilationW, int dilationH) override;
  virtual void SpatialDilatedConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & columns, const Tensor & ones, int kW, int kH, int dW, int dH, int padW, int padH, int dilationW, int dilationH, Scalar scale) override;
  virtual void SpatialDilatedConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & columns, const Tensor & ones, int kW, int kH, int dW, int dH, int padW, int padH, int dilationW, int dilationH, Scalar scale) override;
  virtual void SpatialMaxPooling_updateOutput(const Tensor & input, const Tensor & output, const Tensor & indices, int kW, int kH, int dW, int dH, int padW, int padH, bool ceil_mode) override;
  virtual void SpatialMaxPooling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & indices, int kW, int kH, int dW, int dH, int padW, int padH, bool ceil_mode) override;
  virtual void SpatialDilatedMaxPooling_updateOutput(const Tensor & input, const Tensor & output, const Tensor & indices, int kW, int kH, int dW, int dH, int padW, int padH, int dilationW, int dilationH, bool ceil_mode) override;
  virtual void SpatialDilatedMaxPooling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & indices, int kW, int kH, int dW, int dH, int padW, int padH, int dilationW, int dilationH, bool ceil_mode) override;
  virtual void SpatialMaxUnpooling_updateOutput(const Tensor & input, const Tensor & output, const Tensor & indices, int owidth, int oheight) override;
  virtual void SpatialMaxUnpooling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & indices, int owidth, int oheight) override;
  virtual void SpatialSubSampling_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, int kW, int kH, int dW, int dH) override;
  virtual void SpatialSubSampling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, int kW, int kH, int dW, int dH) override;
  virtual void SpatialSubSampling_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, int kW, int kH, int dW, int dH, Scalar scale) override;
  virtual void SpatialUpSamplingNearest_updateOutput(const Tensor & input, const Tensor & output, int scale_factor) override;
  virtual void SpatialUpSamplingNearest_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, int scale_factor) override;
  virtual void SpatialUpSamplingBilinear_updateOutput(const Tensor & input, const Tensor & output, int outputHeight, int outputWidth) override;
  virtual void SpatialUpSamplingBilinear_updateGradInput(const Tensor & gradOutput, const Tensor & gradInput, int nbatch, int nchannels, int inputHeight, int inputWidth, int outputHeight, int outputWidth) override;
  virtual void SpatialGridSamplerBilinear_updateOutput(const Tensor & input, const Tensor & grid, const Tensor & output) override;
  virtual void SpatialGridSamplerBilinear_updateGradInput(const Tensor & input, const Tensor & gradInput, const Tensor & grid, const Tensor & gradGrid, const Tensor & gradOutput) override;
  virtual void VolumetricAveragePooling_updateOutput(const Tensor & input, const Tensor & output, int kT, int kW, int kH, int dT, int dW, int dH) override;
  virtual void VolumetricAveragePooling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, int kT, int kW, int kH, int dT, int dW, int dH) override;
  virtual void VolumetricConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & finput, const Tensor & fgradInput, int dT, int dW, int dH, int pT, int pW, int pH) override;
  virtual void VolumetricConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & finput, const Tensor & fgradInput, int dT, int dW, int dH, int pT, int pW, int pH) override;
  virtual void VolumetricConvolution_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & finput, int dT, int dW, int dH, int pT, int pW, int pH) override;
  virtual void VolumetricConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & finput, const Tensor & fgradInput, int dT, int dW, int dH, int pT, int pW, int pH, Scalar scale) override;
  virtual void VolumetricConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & finput, const Tensor & fgradInput, int dT, int dW, int dH, int pT, int pW, int pH, Scalar scale) override;
  virtual void VolumetricConvolutionMM_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & finput, int kT, int kW, int kH, int dT, int dW, int dH, int pT, int pW, int pH) override;
  virtual void VolumetricConvolutionMM_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & finput, int kT, int kW, int kH, int dT, int dW, int dH, int pT, int pW, int pH) override;
  virtual void VolumetricConvolutionMM_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & finput, const Tensor & fgradInput, int kT, int kW, int kH, int dT, int dW, int dH, int pT, int pW, int pH) override;
  virtual void VolumetricConvolutionMM_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & finput, int kT, int kW, int kH, int dT, int dW, int dH, int pT, int pW, int pH, Scalar scale) override;
  virtual void VolumetricConvolutionMM_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & finput, int kT, int kW, int kH, int dT, int dW, int dH, int pT, int pW, int pH, Scalar scale) override;
  virtual void VolumetricFractionalMaxPooling_updateOutput(const Tensor & input, const Tensor & output, int outputT, int outputW, int outputH, int poolSizeT, int poolSizeW, int poolSizeH, const Tensor & indices, const Tensor & randomSamples) override;
  virtual void VolumetricFractionalMaxPooling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, int outputT, int outputW, int outputH, int poolSizeT, int poolSizeW, int poolSizeH, const Tensor & indices) override;
  virtual void VolumetricFullConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & finput, const Tensor & fgradInput, int dT, int dW, int dH, int pT, int pW, int pH, int aT, int aW, int aH) override;
  virtual void VolumetricFullConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & finput, const Tensor & fgradInput, int dT, int dW, int dH, int pT, int pW, int pH, int aT, int aW, int aH) override;
  virtual void VolumetricFullConvolution_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & finput, const Tensor & fgradInput, int dT, int dW, int dH, int pT, int pW, int pH, int aT, int aW, int aH) override;
  virtual void VolumetricFullConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & finput, const Tensor & fgradInput, int dT, int dW, int dH, int pT, int pW, int pH, int aT, int aW, int aH, Scalar scale) override;
  virtual void VolumetricFullConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & finput, const Tensor & fgradInput, int dT, int dW, int dH, int pT, int pW, int pH, int aT, int aW, int aH, Scalar scale) override;
  virtual void VolumetricDilatedConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & bias, const Tensor & columns, const Tensor & ones, int kT, int kW, int kH, int dT, int dW, int dH, int padT, int padW, int padH, int dilationT, int dilationW, int dilationH) override;
  virtual void VolumetricDilatedConvolution_updateOutput(const Tensor & input, const Tensor & output, const Tensor & weight, const Tensor & columns, const Tensor & ones, int kT, int kW, int kH, int dT, int dW, int dH, int padT, int padW, int padH, int dilationT, int dilationW, int dilationH) override;
  virtual void VolumetricDilatedConvolution_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & weight, const Tensor & gradColumns, int kT, int kW, int kH, int dT, int dW, int dH, int padT, int padW, int padH, int dilationT, int dilationW, int dilationH) override;
  virtual void VolumetricDilatedConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & gradBias, const Tensor & columns, const Tensor & ones, int kT, int kW, int kH, int dT, int dW, int dH, int padT, int padW, int padH, int dilationT, int dilationW, int dilationH, Scalar scale) override;
  virtual void VolumetricDilatedConvolution_accGradParameters(const Tensor & input, const Tensor & gradOutput, const Tensor & gradWeight, const Tensor & columns, const Tensor & ones, int kT, int kW, int kH, int dT, int dW, int dH, int padT, int padW, int padH, int dilationT, int dilationW, int dilationH, Scalar scale) override;
  virtual void VolumetricMaxPooling_updateOutput(const Tensor & input, const Tensor & output, const Tensor & indices, int kT, int kW, int kH, int dT, int dW, int dH, int pT, int pW, int pH, bool ceilMode) override;
  virtual void VolumetricMaxPooling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & indices, int kT, int kW, int kH, int dT, int dW, int dH, int pT, int pW, int pH, bool ceilMode) override;
  virtual void VolumetricDilatedMaxPooling_updateOutput(const Tensor & input, const Tensor & output, const Tensor & indices, int kT, int kW, int kH, int dT, int dW, int dH, int pT, int pW, int pH, int dilationT, int dilationW, int dilationH, bool ceilMode) override;
  virtual void VolumetricDilatedMaxPooling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & indices, int kT, int kW, int kH, int dT, int dW, int dH, int pT, int pW, int pH, int dilationT, int dilationW, int dilationH, bool ceilMode) override;
  virtual void VolumetricMaxUnpooling_updateOutput(const Tensor & input, const Tensor & output, const Tensor & indices, int oT, int oW, int oH, int dT, int dW, int dH, int pT, int pW, int pH) override;
  virtual void VolumetricMaxUnpooling_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & indices, int oT, int oW, int oH, int dT, int dW, int dH, int pT, int pW, int pH) override;
  virtual void SpatialReflectionPadding_updateOutput(const Tensor & input, const Tensor & output, int pad_l, int pad_r, int pad_t, int pad_b) override;
  virtual void SpatialReflectionPadding_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, int pad_l, int pad_r, int pad_t, int pad_b) override;
  virtual void SpatialReplicationPadding_updateOutput(const Tensor & input, const Tensor & output, int pad_l, int pad_r, int pad_t, int pad_b) override;
  virtual void SpatialReplicationPadding_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, int pad_l, int pad_r, int pad_t, int pad_b) override;
  virtual void VolumetricReplicationPadding_updateOutput(const Tensor & input, const Tensor & output, int pleft, int pright, int ptop, int pbottom, int pfront, int pback) override;
  virtual void VolumetricReplicationPadding_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, int pleft, int pright, int ptop, int pbottom, int pfront, int pback) override;
  virtual void VolumetricUpSamplingNearest_updateOutput(const Tensor & input, const Tensor & output, int scale_factor) override;
  virtual void VolumetricUpSamplingNearest_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, int scale_factor) override;
  virtual void VolumetricUpSamplingTrilinear_updateOutput(const Tensor & input, const Tensor & output, int outputDepth, int outputHeight, int outputWidth) override;
  virtual void VolumetricUpSamplingTrilinear_updateGradInput(const Tensor & gradOutput, const Tensor & gradInput, int nbatch, int nchannels, int inputDepth, int inputHeight, int inputWidth, int outputDepth, int outputHeight, int outputWidth) override;
  virtual void SpatialCrossMapLRN_updateOutput(const Tensor & input, const Tensor & output, const Tensor & scale, int size, Scalar alpha, Scalar beta, Scalar k) override;
  virtual void SpatialCrossMapLRN_updateGradInput(const Tensor & input, const Tensor & gradOutput, const Tensor & gradInput, const Tensor & scale, const Tensor & output, int size, Scalar alpha, Scalar beta, Scalar k) override;


private:
  Tensor & checked_unpack(const Tensor & t, const char * name, int pos) const;

private:
  Type* baseType;
};

} // namespace at
